### PR TITLE
Updates the regex dependency for newer versions

### PR DESCRIPTION
**Pull request by PMunch**
This updates the regex dependency for docopt so it works with newer
versions of Nim.

### CODE REVIEW

**Comment by PMunch** [comment]
Travis failure not related, seems to be set up incorrectly

**Comment by oprypin** [comment]
Wait, so what is the problem? The version is specified to be greater or equal, but surely by default the latest version will be installed?

**Comment by PMunch** [comment]
Yes, but when I installed the docopt package on my machine I had a version of the regex package that was greater than the specified version, so it didn't trigger nimble to install a newer version. But this version was still too old to work with docopt, so I found the lowest version working with docopt on the latest stable release of Nim and bumped the dependency to that.

**Comment by oprypin** [comment]
Thanks!

**Pull request merged**
